#+TITLE: Proyecto01
#+author: Karyme Ivette García, Ui Chul Shin, Alberto Natanael Medel Piña.
#+date: 8 de marzo de 2022

* TODO DESARROLLO
El problema principal es entregar un informe del clima de la ciudad de salida y de la ciudad
de llegada para cada 3 mil boletos de avión que salen el mismo día que se ejecuta el algoritmo.

Debemos cumplir con:
** [ ] Explicar el procedimiento de forma escrita (para eso es este Org).

** [ ] Utilizar un /Web service/ para consultar el clima.
Propuesta: usar [[https://openweathermap.org/][Openweathermap]] pues se integra muy bien con python y parece sencillo de realizar
llamadas a la ==API==.

** [ ] ¿Dónde podría fallar la aplicación? ¿Cómo manejar los errores?

** [ ] Pruebas a la solución.
Son mínimo 3, claramente documentadas.

** [ ] Documentación del proyecto.

** [ ] Modelar un caché (Diosmio eso cómo se hace...?)

* FORMATO DE ENTREGA
Debemos entregarlo en una carpeta llamada ==Tarea01==. La estructura del proyecto es libre.
Podemos hacer uso de cualquier biblioteca y de ser posible integrar una GUI.

Es *obligatorio* poner un ==README.md== que explique la ejecución de la solución.

También hay que realizar un ==PDF== con lo siguiente:

*** [ ] Definición del problema.
*** [ ] Análisis del problema.
*** [ ] Selección de la mejor alternativa.
*** [ ] Diagrama de flujo o pseudocódigo explicado.
*** [ ] Características a futuro de la solución.
